Fix configure.ac to use the same compiler and flags as R. Enable LTO.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1739,6 +1739,15 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
+: ${R_HOME=`R RHOME`}
+if test -z "${R_HOME}"; then
+  echo "could not determine R_HOME"
+  exit 1
+fi
+CC=`"${R_HOME}/bin/R" CMD config CC`
+CFLAGS=`"${R_HOME}/bin/R" CMD config CFLAGS`
+CPPFLAGS=`"${R_HOME}/bin/R" CMD config CPPFLAGS`
+
 # Checks for common programs using default macros
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
